version: '3.3'

services:
  web:
    image: 127.0.0.1:5000/coupon-clipper-stopandshop
    build: .
    environment: &web_env
      ENVIRONMENT: production
      LOG_LEVEL: verbose
      APP_DOMAIN: coupon-clipper-stopandshop.carlyzach.com
    ports:
      - "6091:6091"
    secrets: &web_secrets
      - source: coupon-clipper-stopandshop_session_secret_v1
        target: session_secret
      - source: coupon-clipper-stopandshop_database_url_v2
        target: database_url
      - source: g_email_username_v1
        target: email_username
      - source: g_email_password_v1
        target: email_password
      - source: g_email_server_addr_v1
        target: email_server_addr
      - source: g_email_from_v1
        target: email_from
      - source: coupon-clipper-stopandshop_crypt_keeper_key_v1
        target: crypt_keeper_key
  worker:
    image: 127.0.0.1:5000/coupon-clipper-stopandshop
    environment:
      *web_env
    command: ["coupon-checker"]
    secrets:
      *web_secrets

secrets:
  coupon-clipper-stopandshop_session_secret_v1:
    external: true
  coupon-clipper-stopandshop_database_url_v2:
    external: true
  coupon-clipper-stopandshop_crypt_keeper_key_v1:
    external: true
  g_email_username_v1:
    external: true
  g_email_password_v1:
    external: true
  g_email_server_addr_v1:
    external: true
  g_email_from_v1:
    external: true
